version: 2.1

orbs:
  cypress: cypress-io/cypress@1.1.0

jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm ci
      - run: npm test
  lint:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

workflows:
  build:
    jobs:
      - test
      - cypress/run:
          requires:
            - test
            - lint
          start: "npm start"
          wait-on: "http://localhost:8000"
