version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
workflows:
  unittests:
    jobs:
      - tests:
          description: 'Jest Unit Tests'
          steps:
            - run: npm test

  build:
    jobs:
      - cypress/install:
          build: npm run build

      - cypress/run:
          requires:
            - cypress/install
          start: 'npm start'
          wait-on: 'http://localhost:8000'
