version: 2.1

orbs:
  cypress: cypress-io/cypress@1.1.0

jobs:
  test:
    docker:
      - image: cypress/base:10
    steps:
      - run: npm test

workflows:
  build:
    jobs:
      - cypress/install:
          build: npm run build
      - test
      - cypress/run:
          requires:
            - cypress/install
            - test
          start: 'npm start'
          wait-on: 'http://localhost:8000'
