version: 2.1

orbs:
  cypress: cypress-io/cypress@1.1.0

jobs:
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: cypress/base:10
    steps:
      - run: npm test
      - run: npm ci

workflows:
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - cypress/run:
          requires:
            - test
          start: 'npm start'
          wait-on: 'http://localhost:8000'
