version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
workflows:
  build:
    jobs:
      - cypress/install:
          build: npm run build

      - unittests:
          description: 'Jest Unit Tests'
          parameters:
            to:
              type: string
              default: 'Running Unit tests'
          steps:
            - run: echo << parameters.to >> npm test

      - cypress/run:
          requires:
            - cypress/install
          start: 'npm start'
          wait-on: 'http://localhost:8000'
